version: "3"

services:
  app:
    build: .
    ports:
      - "9876:9876"
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trustwise

volumes:
  db-data: